services:
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow

  mlflow:
    build: ./mlflow
    ports:
      - "5001:5000"
    expose:
      - 5000
